security:
  oauth2:
    client:
      clientId: account-service
      client-secret: my-account-service-password
      accessTokenUri: http://gateway/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  zipkin:
    sender:
      type: web

server:
  servlet:
    context-path: /accounts

feign:
  hystrix:
    enabled: true

